vim.keymap.set({ "n", "x" }, "j", function()
    local keys = table.concat({
        vim.v.count > 0 and vim.v.count or "",
        vim.v.count > 0 and "j" or "gj",
    })
    vim.api.nvim_feedkeys(keys, "n", false)
end)
vim.keymap.set({ "n", "x" }, "k", function()
    local keys = table.concat({
        vim.v.count > 0 and vim.v.count or "",
        vim.v.count > 0 and "k" or "gk",
    })
    vim.api.nvim_feedkeys(keys, "n", false)
end)
vim.keymap.set("n", "<C-s>", "<cmd>wincmd s<CR>")
vim.keymap.set("n", "<C-v>", "<cmd>wincmd v<CR>")
vim.keymap.set("n", "<C-h>", "<cmd>wincmd h<CR>")
vim.keymap.set("n", "<C-j>", "<cmd>wincmd j<CR>")
vim.keymap.set("n", "<C-k>", "<cmd>wincmd k<CR>")
vim.keymap.set("n", "<C-l>", "<cmd>wincmd l<CR>")
vim.keymap.set("n", "<Esc>", "<cmd>noh<cr>")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<A-j>", ":move '>+1<CR>gv=gv")
vim.keymap.set("v", "<A-k>", ":move '<-2<CR>gv=gv")
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
vim.keymap.set("n", "gD", function()
    vim.lsp.buf.declaration()
end)
vim.keymap.set("n", "gd", function()
    vim.lsp.buf.definition()
end)
vim.keymap.set("n", "K", function()
    vim.lsp.buf.hover()
end)
vim.keymap.set("n", "gi", function()
    vim.lsp.buf.implementation()
end)
vim.keymap.set("n", "<F2>", function()
    vim.lsp.buf.rename()
end)
vim.keymap.set("n", "<F4>", function()
    vim.lsp.buf.code_action()
end)
vim.keymap.set("n", "gr", function()
    vim.lsp.buf.references()
end)
vim.keymap.set("n", "gl", function()
    vim.diagnostic.open_float()
end)
vim.keymap.set("n", "[d", function()
    vim.diagnostic.jump({
        count = 1,
    })
end)
vim.keymap.set("n", "]d", function()
    vim.diagnostic.jump({
        count = -1,
    })
end)
