from .battery import Battery
from .bottom_bar import BottomBar
from .clock import Clock
from .cpu import Cpu
from .memory import Memory
from .top_bar import TopBar
from .tray import Tray
from .volume import Volume
from .windows import Windows
from .wlan import Wlan
from .workspaces import Workspaces
